apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: java-docker-app
    component: frontend
  type: LoadBalancer
  ports:
    - name: frontend
      port: 80
      targetPort: 80
